empty开发及优化
thundersdata-frontend/td-design pull request #111
Opened 2020-09-23 12:08 UTC by tunshiyu

2020-09-23 12:20 UTC, RuanXuSong commented on packages/react-native/components/empty/index.tsx
> +    img?: string | ReactNode;
ReactNode包含了string，可以去掉

2020-09-23 12:20 UTC, RuanXuSong commented on packages/react-native/components/empty/index.tsx
> +      flex: isFill ? 1 : 0,
可以直接在 Box 的属性里面设置 flexDirection... 这些

2020-09-23 12:20 UTC, RuanXuSong commented on packages/react-native/components/empty/index.tsx
> +    <Box>{children}</Box>
感觉 isEmpty 为 false的时候没必要在外面套一层 Box

2020-09-24 02:24 UTC, chj-damon requested changes

2020-09-24 02:24 UTC, chj-damon commented on packages/react-native/components/empty/index.tsx
> +    ...restProps,
这里的restProps有点问题。这里的props是作用在Box上的，也就意味着你实际上需要把Empty的自定义属性全部过滤掉。所以这里应该写成这样：
const { isEmpty, emptyText = '暂无数据', imgStyle, isFill, backgroundColor = 'emptyBgColor', img, ...boxProps } = restProps;

const props = useRestyle(restyleFunctions, {
	flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: isFill ? 1 : 0,
    backgroundColor,
    ...boxProps,
});

2020-09-25 02:07 UTC, chj-damon requested changes
图片默认宽高140，跟设计稿对不上吧？我看设计稿上面是215*193

2020-09-25 02:07 UTC, chj-damon commented on packages/react-native/components/empty/index.tsx
> +      return <Text color="emptyTextColor">{emptyText}</Text>;
原来UI没有标注，我让他改了。看一下设计稿。这里直接用variant

2020-09-27 04:00 UTC, chj-damon requested changes

2020-09-27 06:46 UTC, chj-damon approved these changes

2020-09-27 06:46 UTC, chj-damon commented
冲突解决一下

2020-09-27 06:56 UTC, tunshiyu commented
> 冲突解决一下

解决好了

2020-09-27 07:03 UTC, merged