feat: 完成ListItem组件
thundersdata-frontend/td-design pull request #119
Opened 2020-09-27 10:58 UTC by qqack

2020-09-28 08:15 UTC, chj-damon requested changes

2020-09-28 08:15 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  isError?: boolean;
这个不需要。

2020-09-28 08:15 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  multipleLine?: boolean;
这个不需要

2020-09-28 08:15 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  arrow?: boolean;
枚举。参考antd mobile

2020-09-28 08:15 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +    <Text
varient

2020-11-23 03:57 UTC, chj-damon requested changes

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +import { Flex } from '..';
import Flex from '../flex';

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +const IconMap = {
iconMap

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +const alignMapFun = (align: string): 'flex-start' | 'flex-end' | 'center' => {
可以简化：
const alignItemMap = {
  top: 'flex-start',
  bottom: 'flex-end',
  center: 'center',
};

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  align?: 'top' | 'middle' | 'bottom';
keyof alignItemMap

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +    <Box style={{ paddingBottom: theme.spacing.s, marginTop: -theme.spacing.m }}>
这里的样式是为了什么效果？

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +                  width: px(36),
定义一个SIZE的常量

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +    <Flex flexDirection="column" justifyContent="flex-start" alignItems="flex-start">
如果没记错的话，justifyContent和alignItems默认就是flex-start吧

2020-11-23 03:57 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  let numberOfLines = {};
合并成一个三目运算

2020-11-25 03:54 UTC, qqack commented on packages/react-native/components/listItem/index.tsx
> +    <Flex flexDirection="column" justifyContent="flex-start" alignItems="flex-start">
alignItems默认是center

2020-11-25 06:18 UTC, qqack commented on packages/react-native/components/listItem/index.tsx
> +    <Box style={{ paddingBottom: theme.spacing.s, marginTop: -theme.spacing.m }}>
为了把副标题跟主标题不要有太大的间隙

2020-11-25 07:46 UTC, chj-damon requested changes

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  title: ReactNode | string;
ReactNode类型已经包含了string

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  thumb?: ReactNode | null;
thumb加?的话表示它可能是undefined, 所以没必要再加一个null

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +  children?: ReactNode;
children不需要明写，因为FC自带children

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +interface BriefBasePropsType {
只有一个wrap, 可以直接type BriefBasePropsType = Pick< CustomItemProps, 'wrap'>

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +          style={
style={[{width: THUMB_SIZE, height: THUMB_SIZE}, wrap ? {} : {marginRight: theme.spacing.m}]

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +      <Box style={{ flex: 1, flexDirection: 'column' }}>
View/Box 本身就是flexDirection: 'column'的，不需要写。

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +            paddingLeft: theme.spacing.m,
paddingHorizontal

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +            borderBottomWidth: StyleSheet.hairlineWidth,
import { ONE_PIXEL } from '../helper';

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +          <Box style={{ flex: 1, flexDirection: 'row', alignItems: 'center' }}>
直接用Flex更合适

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +                  paddingTop: theme.spacing.m,
paddingVertical

2020-11-25 07:46 UTC, chj-damon commented on packages/react-native/components/listItem/index.tsx
> +                  height: '100%',
这个height不写应该也没事吧

2020-11-25 08:45 UTC, chj-damon approved these changes

2020-11-25 09:03 UTC, merged