feat: 完成header组件
thundersdata-frontend/td-design pull request #152
Opened 2020-11-30 11:48 UTC by SunshineH2

2020-12-01 02:18 UTC, chj-damon requested changes

2020-12-01 02:18 UTC, chj-damon commented on packages/react-native/components/header/index.tsx
> +  const height = px(50);
单独设一个height可能会有问题。比如传入的headerHeight比50大。

2020-12-01 02:18 UTC, chj-damon commented on packages/react-native/components/header/index.tsx
> +    <View
能不能用Flex

2020-12-01 02:18 UTC, chj-damon commented on packages/react-native/components/header/index.tsx
> +        <Text
怎么不用组件库里的Text？

2020-12-01 02:18 UTC, chj-damon commented on packages/react-native/components/header/index.tsx
> +      <Flex flex={1} justifyContent="flex-end" alignItems="center">
alignItems默认就是center

2020-12-03 02:32 UTC, chj-damon requested changes

2020-12-03 02:32 UTC, chj-damon commented on packages/react-native/components/animate-header/index.tsx
> +  y?: Animated.Value<0>;
<number>

2020-12-03 02:32 UTC, chj-damon commented on packages/react-native/components/animate-header/index.tsx
> +  scope?: number;
换个变量名。scope词不达意

2020-12-03 02:32 UTC, chj-damon commented on packages/react-native/components/animate-header/index.tsx
> +  const opacity = interpolate(y, {
不是说opacity有问题吗？

2020-12-03 02:32 UTC, chj-damon commented on packages/react-native/components/animate-header/index.tsx
> +        <Animated.View style={{ opacity, flex: 5, alignItems: 'center' }}>
这里需要设opacity吗

2020-12-03 02:32 UTC, chj-damon commented on packages/react-native/components/index.ts
> +import AnimateHeader from './animate-header';
把AnimateHeader作为ImageHeader的子组件。

export default Object.assign(ImageHeader, {AnimateHeader});

2020-12-03 03:52 UTC, SunshineH2 commented on packages/react-native/components/animate-header/index.tsx
> +  const opacity = interpolate(y, {
测试了没有问题

2020-12-03 05:40 UTC, chj-damon approved these changes

2020-12-03 05:50 UTC, merged