feat: 优化buttonGroup组件以及更新相关文档
thundersdata-frontend/td-design pull request #189
Opened 2020-12-12 10:03 UTC by qqack

2020-12-12 10:53 UTC, chj-damon requested changes

2020-12-12 10:53 UTC, chj-damon commented on packages/react-native/src/button-group/index.md
> +| size           | `false` | 尺寸                    | `xxs` \| `xs` \| `s` \| `m` \| `l` \| `xl` \| `xxl` | `m`    |
多了一个m

2020-12-12 10:53 UTC, chj-damon commented on packages/react-native/src/button-group/index.md
> +| disabledItems  | `false` | 设置禁用的项            | `number[]`                                          |        |
补充一下说明：设置禁用的项，值为options的数组下标

2020-12-14 02:06 UTC, qqack commented on packages/react-native/src/button-group/index.md
> +| size           | `false` | 尺寸                    | `xxs` \| `xs` \| `s` \| `m` \| `l` \| `xl` \| `xxl` | `m`    |
最后那个m是默认值

2020-12-14 03:02 UTC, merged