fix: 修正Badge組件顯示位置總是在子組件範圍內
thundersdata-frontend/td-design pull request #576
Opened 2023-02-19 04:49 UTC by 821wkli

@chj-damon 
@chen929104 

### Problem

Badge 組件實際顯示位置和官方的文檔的example不一樣

如下圖, 原因是把right 和 top 固定了0

<img width="299" alt="Screenshot 2023-02-19 at 12 44 31 PM" src="https://user-images.githubusercontent.com/42508279/219922695-2c1882fe-9eb8-4620-8af5-153b772fb66f.png">

### Expected output

badge container 的一半應該是在子組件之外，這是修正後的效果

<img width="299" alt="image" src="https://user-images.githubusercontent.com/42508279/219922796-b0d070db-85f6-491c-90a5-2d2b73b8bf18.png">

2023-02-19 11:34 UTC, chj-damon commented
非常感谢！我明天review一下

2023-02-20 01:35 UTC, chj-damon requested changes

2023-02-20 01:35 UTC, chj-damon commented on packages/react-native/src/badge/useBadge.tsx
> +    [text]
这里的依赖项不应该是text，应该是这个函数里面用到的state或者props，所以是badgeOffset.top 和 badgeOffset.right

2023-02-20 02:34 UTC, 821wkli commented on packages/react-native/src/badge/useBadge.tsx
> +    [text]
已更新

2023-02-20 04:36 UTC, chj-damon commented
冲突解决一下就OK了

2023-02-20 04:48 UTC, 821wkli commented
> 冲突解决一下就OK了

已resolved

2023-02-20 05:59 UTC, merged